---
- name: Nginx Install and Config
  import_tasks: nginx.yml

- name: Wordpress Install and Config
  import_tasks: wordpress.yml

- name: Iptables Hardening
  import_tasks: iptables.yml

- name: Install Exporter for Monitoring
  import_tasks: install_exporter.yml
