---
- name: Nginx Install Required Packages
  apt:
    name:
      - nginx
    state: latest
    update_cache: yes

- name: Copy Letsencrypt Certificate Files
  copy:
    src: letsencrypt/
    dest: "{{ letsencrypt_dir }}"
    directory_mode:
    owner: root
    group: root
    mode: 700

- name: Find all config files
  shell: ls -1 /etc/nginx/sites-enabled
  register: contents

- name: Remove Default Config Files
  file:
    path: "/etc/nginx/sites-enabled/{{ item }}"
    state: absent
  with_items: contents.stdout_lines
  when: item not in nginx_conf_files
  notify: reload nginx

- name: Copy Nginx Config Files
  template:
    src: nginx-config/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
    owner: root
    group: root
    mode: 700
  loop: "{{ nginx_conf_files }}"
  notify: reload nginx

- name: Copy Static Files
  copy:
    src: static/
    dest: /var/www/{{ root_domain_name }}/
    directory_mode:
  notify: reload nginx
