---
# Installing Filebeat

# Add Elasticsearch apt key

- name: Add Elasticsearch apt key
  apt_key:
   url: "{{elasticsearch_repo_gpg_key_url}}"
   state: present

# Add the Elasticsearch apt repo. For versions 7 of the stack - use '7.x-prerelease':

- name: Adding Elasticsearch repo
  apt_repository:
   repo: "deb {{elasticsearch_repo_base_url}}"
   state: present

# Updateing Repository

- name: "Update cache & Full system update"
  apt:
   update_cache: true
   upgrade: dist
   cache_valid_time: 3600
   force_apt_get: true

# Installing Filebeat

- name: Install Filebeat
  apt:
   name: filebeat=7.17.1
   update_cache: yes

# Copy Config File
 
- name: Copy filebeat.yml
  template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    owner: root
    mode: 0744
  notify: restart filebeat
