---
- name: Add Elasticsearch apt key
  apt_key:
   url: "{{elasticsearch_repo_gpg_key_url}}"
   state: present

# Add the Elasticsearch apt repo. For versions 7 of the stack - use '7.x-prerelease':

- name: Adding Elasticsearch repo
  apt_repository:
   repo: "deb {{elasticsearch_repo_base_url}}"
   state: present

- name: Install Filebeat
  apt:
   name: filebeat={{elk_version}}
   update_cache: yes

# Copy Config File
 
- name: Copy filebeat.yml
  template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    owner: root
    mode: 0744
  notify: restart filebeat
