restapi:
  hosts: 192.168.0.129

webserver:
  hosts: 192.168.0.202

dbserver:
  hosts: 192.168.1.204

gateway:
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_ssh_user: root

gateway_pub:
  hosts: 188.121.110.154

elk_server:
  hosts: 185.235.43.181
