---
- import_playbook: gateway.yml
- import_playbook: database.yml
- import_playbook: restApi.yml
- import_playbook: nginx.yml
- import_playbook: elk.yml
- import_playbook: filebeat.yml
- import_playbook: node-exporter.yml
- import_playbook: exporter.yml
- import_playbook: monitoring.yml
