---
- name: Configure Rest Api with Ansible
  hosts: RestApi
  become: True
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist
    - name: Install the package "iptables-persistent"
      apt:
        name: iptables-persistent
    - name: Install the package "python3-venv"
      apt:
        name: python3.8-venv
    - name: Install the package "net-tools"
      apt:
        name: net-tools
    - name: Clone a GitHub Repository
      git:
        repo: https://github.com/Ygn-Amirjani/Phonebook.git
        dest: Phonebook
        clone: yes
        update: yes
    - name: create a virtualenv using the venv module
      command:
        cmd: python3 -m venv ./Phonebook/REST-API/venv
        creates: ./Phonebook/REST-API/venv
    - name: Copy the "create_venv.sh" file to the remote server 
      copy:
        src: ./script/create_venv.sh
        dest: .
        mode: 0755
    - name: Copy the "Rest.service" file to the remote server 
      copy:
        src: ./service-config/Rest.service
        dest: /lib/systemd/system/
    - name: just force systemd to reread configs 
      systemd:
        daemon_reload: yes
    - name: enable service cron on remote server
      systemd: 
        name: Rest
        state: started
        enabled: yes
    - name: Allow related and established connections
      iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
    - name: Allow input package on TCP port 18080
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 18080
        jump: ACCEPT
    - name: Allow input package on TCP port 22 (SSH)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        jump: ACCEPT
    - name: Allow input package on ICMP
      iptables:      
        chain: INPUT
        protocol: icmp
        jump: ACCEPT
    - name: Drop all other packages
      iptables:
        chain: INPUT
        jump: DROP
    - name: SSH Hardening
      copy:
        src: ./ssh-hardening/ssh_hardening_config
        dest: /etc/ssh/sshd_config
    - name: Restart SSHD
      systemd:
        name: sshd
        state: restarted
