route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
    - to: yeganeh.a.m7979@gmail.com
      from: yeganeh.a.m7979@gmail.com
      smarthost: smtp.gmail.com:587
      auth_username: yeganeh.a.m7979@gmail.com
      auth_identity: yeganeh.a.m7979@gmail.com
      auth_password: YgnFrb7998

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
