- name: Download elasticsearch.deb
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elk_version }}-amd64.deb
    dest: /tmp/elasticsearch.deb
  when: "'elasticsearch' not in ansible_facts.packages"

- name: Install elasticsearch.deb package
  apt:
    deb: /tmp/elasticsearch.deb
  when: "'elasticsearch' not in ansible_facts.packages"
  notify: restart es

- name: Copy Elasticsearch
  template:
    src: es/elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    mode: 0744
  notify: restart es
