---
# Installing Elasticsearch

# Add Elasticsearch apt key

- name: Add Elasticsearch apt key
  apt_key:
   url: "{{elasticsearch_repo_gpg_key_url}}"
   state: present

# Add the Elasticsearch apt repo. For versions 7 of the stack - use '7.x-prerelease':

- name: Adding Elasticsearch repo
  apt_repository:
   repo: "deb {{elasticsearch_repo_base_url}}"
   state: present

# Installing Elasticsearch

- name: Install Filebeat
  apt:
   name: elasticsearch= {{elk_version}}
   update_cache: yes


- name: Copy Elasticsearch
  template:
    src: es/elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    mode: 0744
  notify: restart es
