---
- name: Copy netplan Config File
  template:
    src: netplan/50-cloud-init.yaml.j2
    dest: /etc/netplan/50-cloud-init.yaml
    owner: root
    group: root
    mode: 0744
  notify: apply netplan

- name: Force for apply netplan
  meta: flush_handlers

- name: Mysql Install and Config
  import_tasks: database.yml

- name: Backup configuration
  import_tasks: backup.yml

- name: Install exporter
  import_tasks: install_exporter.yml

- name: Iptables Hardening
  import_tasks: iptables.yml

- name: Generate ssh keys
  openssh_keypair:
    path: ~/.ssh/id_rsa

- name: Fetch the keyfile from one server to another
  fetch:
    src: "~/.ssh/id_rsa.pub"
    dest: "id_rsa.pub"
    flat: yes
