---
- name: reload nginx
  service:
    name: nginx
    state: restarted

- name: restore iptables
  shell: "iptables-restore < /etc/iptables/rules.v4"

- name: apply netplan
  command: netplan apply
  async: 45
  poll: 0

- name: just force systemd to reread Monitoring configs
  systemd:
    daemon_reload: yes
    
- name: enable node-exporter service cron on remote server
  systemd:
    name: nginx-exporter
    state: started
    enabled: yes