---
- name: Install the package "python3-venv"
  apt:
    name: python3.8-venv

- name: Clone a GitHub Repository
  git:
    repo: https://github.com/Ygn-Amirjani/Phonebook.git
    dest: Phonebook
    clone: yes
    update: yes

- name: create a virtualenv using the venv module
  command:
    cmd: python3 -m venv ./Phonebook/REST-API/venv
    creates: ./Phonebook/REST-API/venv

- name: Copy the "create_venv.sh" file to the remote server
  copy:
    src: ./roles/basic-code-work/files/create_venv.sh
    dest: .
    mode: 0755
