---
- name: daemon reload
  systemd:
    daemon_reload: yes

- name: start cexporter
  systemd:
    name: cexporter
    state: started
    enabled: yes

- name: restart cexporter
  systemd:
    name: cexporter
    state: restarted
