---
- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: enable service cron on remote server
  systemd:
    name: Rest
    state: started
    enabled: yes

- name: restore iptables
  shell: "/sbin/iptables-restore < /etc/iptables/rules.v4"

- name: apply netplan
  command: netplan apply
  async: 45
  poll: 0
