---
- name: grafana add gpg key 
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: add repository Grafana
  apt_repository:
    repo: "deb {{ grafana_repo_url }}"
    state: present

- name: Install Grafana
  apt:
    name: grafana={{ grafana_version }}
    update_cache: yes

- name: enable grafana service cron on remote server
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Copy custom_exporter.json in /var/lib/grafana/dashboards
  copy:
    src: dashboards/custom_exporter.json
    dest: /var/lib/grafana/dashboards/custom_exporter.json

- name: create datasource in grafana
  community.grafana.grafana_datasource:
    name: prometheus
    grafana_url: https://grafana.bukhara-chkh.ir
    grafana_user: "admin"
    grafana_password: "admin"
    org_id: "1"
    ds_type: prometheus
    ds_url: https://prometheus.bukhara-chkh.ir
    access: proxy
    is_default: yes
  notify:
    - create dashboards in grafana
    - create custom dashboards in grafana
