---
- name: Install Node-exporter zip file with wget
  get_url:
    url: "{{ node_exporter_download_link }}"
    dest: /root

- name: We create a directory to copy node-exporter file
  file:
    path: /usr/local/bin/node-exporter
    state: directory
    mode: 0777

- name: Extract Node-exporter Zip File
  unarchive:
    src: /root/{{ node_exporter_file }}.tar.gz
    dest: /usr/local/bin/node-exporter
    remote_src: yes
