---
- name: Install Prometheus zip file with wget
  get_url:
    url: "{{ prometheus_download_link }}"
    dest: /root

- name: We create a directory to copy prometheus file
  file:
    path: /usr/local/bin/prometheus
    state: directory
    mode: 0777

- name: Extract Prometheus Zip File
  unarchive:
    src: /root/{{ prometheus_file }}.tar.gz
    dest: /usr/local/bin/prometheus
    remote_src: yes

- name: Copy the alert rules to the remote server
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/prometheus
  loop:
    - alert_configs/elasticsearch_alerts.yml
    - alert_configs/identical_alerts.yml
    - alert_configs/mysql_alerts.yml
    - alert_configs/nginx_alerts.yml
    - alert_configs/prometheus_alerts.yml

- name: Copy the main file of Prometheus 
  copy:
    src: main-file/prometheus.yml
    dest: /usr/local/bin/prometheus

- name: build Prometheus.service
  copy:
    src: service/prometheus.service
    dest: /lib/systemd/system/

- name: just force systemd ro reload service
  systemd:
    daemon_reload: yes

- name: enable Prometheus service cron on remote server
  systemd:
    name: prometheus
    state: started
    enabled: yes
