---
- name: Copy the "Rest.service" file to the remote server
  copy:
    src: Rest.service
    dest: /lib/systemd/system/
  notify:
    - just force systemd to reread configs
    - enable service cron on remote server
