---
backup_host: "{{ gateway_private_ip_eth2 }}"
backup_user: root

db_users:
  - { username: arvan, password: arvan, db: "*" }
  - { username: wordpress, password: wordpress, db: wordpress }

dbs:
  - wordpress

backup_keep_days: 5

open_input_ports: [9110, 9093, 9104, 9100]
