---
- name: create dashboards in grafana
  community.grafana.grafana_dashboard:
    grafana_url: https://grafana.bukhara-chkh.ir
    grafana_user: "admin"
    grafana_password: "admin"
    org_id: "1"
    dashboard_id: "{{ item }}"
  loop:
    - "13978"
    - "12708"
    - "14057"
    - "14191"

- name: apply netplan
  command: netplan apply
  async: 45
  poll: 0

