---
- name: create dashboards in grafana
  community.grafana.grafana_dashboard:
    grafana_url: "{{ grafana_url }}"
    grafana_user: "admin"
    grafana_password: "admin"
    org_id: "1"
    dashboard_id: "{{ item }}"
  loop:
    - "13978"
    - "12708"
    - "14057"
    - "14191"

- name: create custom dashboards in grafana
  community.grafana.grafana_dashboard:
    grafana_url: "{{ grafana_url }}"
    grafana_user: "admin"
    grafana_password: "admin"
    org_id: "1"
    state: present
    commit_message: create custom dashboard
    overwrite: yes
    path: /var/lib/grafana/dashboards/custom_exporter.json    

- name: apply netplan
  command: netplan apply
  async: 45
  poll: 0

