---
- name: restart mysql
  service:
    name: mysql
    state: restarted

- name: restore iptables
  shell: "iptables-restore < /etc/iptables/rules.v4"

- name: apply netplan
  command: netplan apply
  async: 45
  poll: 0
