{
 "title": "custom exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{job=\"exporter\", instance=\"192.168.0.2:9110\"}"
    }
   ]
  },
  {
   "title": "Gateway Accessibility",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "gateway_accessibility{job=\"exporter\", instance=\"192.168.0.2:9110\"}"
    }
   ]
  },
  {
   "title": "Internet connection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "internet_connection{job=\"exporter\", instance=\"192.168.0.2:9110\"}"
    }
   ]
  },
  {
   "title": "DNS Check",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dns_check{job=\"exporter\", instance=\"192.168.0.2:9110\"}"
    }
   ]
  },
  {
   "title": "Nginx Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "nginx_availability{job=\"exporter\", instance=\"192.168.0.2:9110\"}"
    }
   ]
  },
  {
   "title": "Restapi Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "restapi_availability{job=\"exporter\", instance=\"192.168.0.2:9110\"}"
    }
   ]
  },
  {
   "title": "Process Start Time Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"exporter\", instance=\"192.168.0.2:9110\"}"
    }
   ]
  },
  {
   "title": "Process Virtual Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"exporter\", instance=\"192.168.0.2:9110\"}"
    }
   ]
  }
 ]
}